# This workflow runs all tests on cassandra to ensure full compatibility
name: Cassandra tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup 3-node Cassandra cluster
      run: |
        docker-compose -f test/cluster/cassandra/docker-compose.yml up -d
      # A separate step for building to separate measuring time of compilation and testing
    - name: Build the project
      run: cargo build --verbose --tests
    - name: Run tests on cassandra
      run: |
        CDC='disabled' SCYLLA_URI=172.42.0.2:9042 SCYLLA_URI2=172.42.0.3:9042 SCYLLA_URI3=172.42.0.4:9042 cargo test --verbose -- --skip test_views_in_schema_info --test-threads 1
    - name: Stop cluster
      run: docker-compose -f test/cluster/cassandra/docker-compose.yml down
